import {
  Anchor,
  Aperture,
  Award,
  Banknote,
  Bitcoin,
  Blocks,
  BookOpen,
  Boxes,
  Brain,
  Briefcase,
  BriefcaseBusiness,
  Brush,
  Bug,
  Building,
  Building2,
  Calculator,
  CalendarDays,
  Car,
  ChartColumn,
  ChartLine,
  ChartPie,
  ChefHat,
  ClipboardList,
  Cloud,
  Code,
  Coffee,
  Component,
  Compass,
  Construction,
  Cpu,
  CreditCard,
  Database,
  Droplets,
  Dumbbell,
  Eraser,
  Euro,
  Factory,
  FileSignature,
  FileText,
  Film,
  Flower2,
  Frame,
  Gift,
  GitBranch,
  Globe,
  GraduationCap,
  Hammer,
  Handshake,
  HardHat,
  Headphones,
  HeartPulse,
  Home,
  Image as ImageIcon,
  Key,
  KeyRound,
  Landmark,
  Languages,
  Layers,
  Layout,
  Leaf,
  Library,
  Lightbulb,
  Mail,
  Map,
  MapPin,
  Megaphone,
  MessageSquare,
  Mic,
  Monitor,
  Music,
  Navigation,
  Network,
  Newspaper,
  Package,
  Paintbrush,
  Palette,
  PartyPopper,
  PawPrint,
  PenLine,
  PenTool,
  PencilRuler,
  PiggyBank,
  Pill,
  Plane,
  Podcast,
  Presentation,
  Puzzle,
  Quote,
  Receipt,
  Recycle,
  Rocket,
  Route,
  Rss,
  Ruler,
  Scale,
  School,
  Search,
  Send,
  Server,
  ShieldCheck,
  Smartphone,
  Snowflake,
  Sparkles,
  Spline,
  Sprout,
  Star,
  Stethoscope,
  Sun,
  Target,
  Terminal,
  Thermometer,
  TrendingUp,
  Trophy,
  Truck,
  UserRound,
  Users,
  UtensilsCrossed,
  Video,
  Wallet,
  WandSparkles,
  Wheat,
  Wifi,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * Icon groups for the Services section (label → icon names). The list is
 * deliberately broad so the app fits any profession — it is shared on
 * GitHub, not tied to one trade. Add new lucide icons here and they will
 * appear everywhere automatically.
 *
 * Isolated in its own module so the ~140-icon registry is bundled in a
 * separate, cacheable chunk instead of being mixed with the site helpers.
 */
export const SERVICE_ICON_GROUPS: { label: string; icons: string[] }[] = [
  {
    label: "Design & créatif",
    icons: [
      "Palette",
      "PenTool",
      "PenLine",
      "Paintbrush",
      "Brush",
      "PencilRuler",
      "Ruler",
      "Layers",
      "Component",
      "Puzzle",
      "Spline",
      "Eraser",
      "Sparkles",
      "WandSparkles",
      "Frame",
      "Aperture",
      "Image",
    ],
  },
  {
    label: "Développement & tech",
    icons: [
      "Code",
      "Terminal",
      "GitBranch",
      "Cpu",
      "Database",
      "Server",
      "Cloud",
      "Network",
      "Wifi",
      "Bug",
      "Blocks",
      "Workflow",
      "Monitor",
      "Smartphone",
      "Layout",
    ],
  },
  {
    label: "Business & conseil",
    icons: [
      "Compass",
      "Briefcase",
      "BriefcaseBusiness",
      "ChartLine",
      "ChartColumn",
      "ChartPie",
      "Presentation",
      "ClipboardList",
      "Handshake",
      "Headphones",
      "Lightbulb",
      "Rocket",
      "Target",
      "TrendingUp",
      "Users",
      "UserRound",
      "Brain",
    ],
  },
  {
    label: "Communication & marketing",
    icons: [
      "Megaphone",
      "Search",
      "Video",
      "Film",
      "Mic",
      "Podcast",
      "Music",
      "Globe",
      "Languages",
      "Newspaper",
      "Quote",
      "MessageSquare",
      "Mail",
      "Send",
      "Rss",
      "BookOpen",
    ],
  },
  {
    label: "Finance & droit",
    icons: [
      "Wallet",
      "Banknote",
      "CreditCard",
      "PiggyBank",
      "Receipt",
      "Calculator",
      "Euro",
      "Bitcoin",
      "Landmark",
      "Scale",
      "FileText",
      "FileSignature",
    ],
  },
  {
    label: "Santé, bien-être & sport",
    icons: [
      "HeartPulse",
      "Stethoscope",
      "Pill",
      "Dumbbell",
      "Flower2",
      "Leaf",
      "Sprout",
      "Sun",
    ],
  },
  {
    label: "Éducation & formation",
    icons: ["GraduationCap", "School", "Library"],
  },
  {
    label: "Immobilier, bâtiment & artisanat",
    icons: [
      "Home",
      "Key",
      "Building2",
      "Building",
      "Hammer",
      "HardHat",
      "Construction",
      "Factory",
      "Wrench",
    ],
  },
  {
    label: "Transport & logistique",
    icons: [
      "Truck",
      "Package",
      "Boxes",
      "Plane",
      "Car",
      "Anchor",
      "Map",
      "MapPin",
      "Route",
      "Navigation",
    ],
  },
  {
    label: "Événementiel, restauration & divers",
    icons: [
      "CalendarDays",
      "PartyPopper",
      "Gift",
      "Trophy",
      "Award",
      "Star",
      "Coffee",
      "ChefHat",
      "UtensilsCrossed",
      "PawPrint",
      "ShieldCheck",
      "KeyRound",
      "Zap",
      "Snowflake",
      "Thermometer",
      "Droplets",
      "Recycle",
      "Wheat",
    ],
  },
];

const serviceIconRegistry: Record<string, LucideIcon> = {
  Palette,
  PenTool,
  PenLine,
  Paintbrush,
  Brush,
  PencilRuler,
  Ruler,
  Layers,
  Component,
  Puzzle,
  Spline,
  Eraser,
  Sparkles,
  WandSparkles,
  Frame,
  Aperture,
  Image: ImageIcon,
  Code,
  Terminal,
  GitBranch,
  Cpu,
  Database,
  Server,
  Cloud,
  Network,
  Wifi,
  Bug,
  Blocks,
  Workflow,
  Monitor,
  Smartphone,
  Layout,
  Compass,
  Briefcase,
  BriefcaseBusiness,
  ChartLine,
  ChartColumn,
  ChartPie,
  Presentation,
  ClipboardList,
  Handshake,
  Headphones,
  Lightbulb,
  Rocket,
  Target,
  TrendingUp,
  Users,
  UserRound,
  Brain,
  Megaphone,
  Search,
  Video,
  Film,
  Mic,
  Podcast,
  Music,
  Globe,
  Languages,
  Newspaper,
  Quote,
  MessageSquare,
  Mail,
  Send,
  Rss,
  BookOpen,
  Wallet,
  Banknote,
  CreditCard,
  PiggyBank,
  Receipt,
  Calculator,
  Euro,
  Bitcoin,
  Landmark,
  Scale,
  FileText,
  FileSignature,
  HeartPulse,
  Stethoscope,
  Pill,
  Dumbbell,
  Flower2,
  Leaf,
  Sprout,
  Sun,
  GraduationCap,
  School,
  Library,
  Home,
  Key,
  Building2,
  Building,
  Hammer,
  HardHat,
  Construction,
  Factory,
  Wrench,
  Truck,
  Package,
  Boxes,
  Plane,
  Car,
  Anchor,
  Map,
  MapPin,
  Route,
  Navigation,
  CalendarDays,
  PartyPopper,
  Gift,
  Trophy,
  Award,
  Star,
  Coffee,
  ChefHat,
  UtensilsCrossed,
  PawPrint,
  ShieldCheck,
  KeyRound,
  Zap,
  Snowflake,
  Thermometer,
  Droplets,
  Recycle,
  Wheat,
};

export const SERVICE_ICON_NAMES = Object.keys(serviceIconRegistry);

export function ServiceIcon({
  name,
  className,
}: {
  name: string;
  className?: string;
}) {
  const Icon = serviceIconRegistry[name] ?? Layers;
  return <Icon className={className} aria-hidden />;
}
